const loginActions = {
  CHECK_USER_REQUESTED: 'CHECK_USER_REQUESTED',
  CHECK_USER_SUCCEED: 'CHECK_USER_SUCCEED',
  CHECK_USER_FAILED: 'CHECK_USER_FAILED',
  REGISTER_USER_REQUESTED: 'REGISTER_USER_REQUESTED',
  REGISTER_USER_SUCCEED: 'REGISTER_USER_SUCCEED',
  REGISTER_USER_FAILED: 'REGISTER_USER_FAILED'
}

export {
  loginActions
}
